"use client";
import { createSvgIcon } from "@mui/joy/utils";
import FlameSvg from "../../../images/icons/flame-blue.svg";
import BulbSvg from "../../../images/icons/electrical-certificate-blue.svg";
import ExitSvg from "../../../images/icons/emergency-exit-blue.svg";
import EnergySvg from "../../../images/icons/energy-performance-blue.svg";
import FireAlarmSvg from "../../../images/icons/fire-alarm-blue.svg";
import FireRiskSvg from "../../../images/icons/fire-risk-assessment-blue.svg";
import HmoSvg from "../../../images/icons/hmo.svg";
import PassedSvg from "../../../images/icons/passed-blue.svg";
import PatSvg from "../../../images/icons/pat-test-blue.svg";
import OpenSvg from "../../../images/icons/open.svg";

import BookingSvg from "@/images/steps/booking.svg";
import CalendarSvg from "@/images/steps/calendar.svg";
import CertificateSvg from "@/images/steps/certificate.svg";
import DoorSvg from "@/images/steps/door.svg";

export const FlameIcon = createSvgIcon(<FlameSvg />, "Flame");
export const BulbIcon = createSvgIcon(<BulbSvg />, "Bulb");
export const ExitIcon = createSvgIcon(<ExitSvg />, "Exit");
export const EnergyIcon = createSvgIcon(<EnergySvg />, "Energy");
export const FireAlarmIcon = createSvgIcon(<FireAlarmSvg />, "FireAlarm");
export const FireRiskIcon = createSvgIcon(<FireRiskSvg />, "FireRisk");
export const HmoIcon = createSvgIcon(<HmoSvg />, "Hmo");
export const PassedIcon = createSvgIcon(<PassedSvg />, "Passed");
export const PatIcon = createSvgIcon(<PatSvg />, "Pat");
export const OpenIcon = createSvgIcon(<OpenSvg />, "Open");
export const BookingIcon = createSvgIcon(<BookingSvg />, "Booking");
export const CalendarIcon = createSvgIcon(<CalendarSvg />, "Calendar");
export const CertificateIcon = createSvgIcon(<CertificateSvg />, "Certificate");
export const DoorIcon = createSvgIcon(<DoorSvg />, "Door");
