import { Inter } from "next/font/google";
import ThemeRegistry from "../_components/theme-registry";
import TopLoader from "../_components/common/top-loader";
import AdminNavigation from "./_components/admin-navigation";
import QueryProvider from "../_components/query-provider";
import { SnackbarProvider } from "../_components/snackbar-provider";
import { Suspense } from "react";
import { Metadata } from "next";
import SnackbarHandler from "../_components/snackbar-handler";

const outfit = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel - London Home Safety",
  description: "Generated by create next app",
  robots: {
    index: false,
  },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <QueryProvider>
          <ThemeRegistry options={{ key: "joy" }}>
            <SnackbarProvider>
              <TopLoader />
              <Suspense>
                <AdminNavigation>
                  <SnackbarHandler />
                  {children}
                </AdminNavigation>
              </Suspense>
            </SnackbarProvider>
          </ThemeRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
