import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Header from "../_components/global/header/header";
import Footer from "../_components/global/footer";
import TopLoader from "../_components/common/top-loader";
import { Suspense } from "react";
import ThemeRegistry from "../_components/theme-registry";
import QueryProvider from "../_components/query-provider";
import { SnackbarProvider } from "../_components/snackbar-provider";
import ReCaptchaProvider from "../_components/recaptcha-provider";
import SnackbarHandler from "../_components/snackbar-handler";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "London Home Safety",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ReCaptchaProvider>
          <QueryProvider>
            <ThemeRegistry options={{ key: "joy" }}>
              <SnackbarProvider>
                <TopLoader />
                <Header />
                <Suspense>
                  <SnackbarHandler />
                  {children}
                </Suspense>
                <Footer />
              </SnackbarProvider>
            </ThemeRegistry>
          </QueryProvider>
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
